# Generated by Django 4.2.5 on 2023-10-26 11:15

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_created_at_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=categories.models.upload_to),
        ),
    ]
