# Generated by Django 4.2.5 on 2023-09-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('valid_till__gte', models.ExpressionWrapper(models.F('valid_till'), output_field=models.DateTimeField()))), name='valid_till_not_less_than_current_datetime'),
        ),
    ]
