# Generated by Django 4.2.5 on 2023-09-16 16:49

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_valid_till_not_less_than_current_datetime"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="valid_till_not_less_than_current_datetime",
        ),
        migrations.AlterField(
            model_name="product",
            name="valid_till",
            field=models.DateTimeField(validators=[products.models.no_past]),
        ),
    ]
