# Generated by Django 4.2.5 on 2023-10-26 11:15

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_image_url_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to=products.models.upload_to),
            preserve_default=False,
        ),
    ]
